### ISSUE TITLE
USER STORY: About us page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#11]
As a **User**, I can find information about the developers so that I can request connections or give feedback.

**Acceptance Criteria:**
1. An about us page is created and styled within the UI/UX guidelines
2. All developers are featured with links to their Github profiles and LinkedIn
3. Team name is prominently featured along with the hackathon title

**Tasks**
- [x] Create a styled about us HTML page
- [x] Create cards for the showcasing the developers
- [x] Add LinkedIn, Github icon links
- [x] Add developer photo (with consent) 
- [x] List the team name and hackathon title
- [ ] Provide brief excerpt of main roles of dev (potential)
