### ISSUE TITLE
USER STORY: Countdown timer

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#111]
As a **User**, I can see a timer so I can see how much time remaining I have to complete a level.

**Acceptance Criteria:**
1. A time should be visible on the game screen
2. The time should count down in correct format
3. the timer shoud fire a game over upon ending

**Tasks**
- [x] Style a timer in mm:ss format
- [x] On game load start the timer 
- [x] When the timer finishes fire the game over function
