### ISSUE TITLE
USER STORY: Level Creation

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#12]
As a **User**, I can select and play level so that I can enter a unique game mode of my choosing .

**Acceptance Criteria:**
1. A level selection screen should be available on the home page or level select page.
2. Links should like to the individual level scenes within the game
3. Levels should be unique and seperate from each other, different sprites/background, music

**Tasks**

- [ ] Add links to level select in the homepage
- [x] Create a configurable new level class scene in Kaboom
- [x] Add relevant sprites, music, audio to level
- [x] Add map layout and enemies to level
- [x] Link game over / victory screens to level

**Comment by SandraBergstrom** [comment]
Working on level 2 - Marios level
