### ISSUE TITLE
CLASSES - Player Class

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#14]
A configurable Player class

**Tasks**
- [x] Create a classes folder
- [x] Add a Player.js file and export the player class
- [x] Add configuration parameters (sprite, speed, bullet etc)
- [x] Ensure movement and shooting functionality is working
- [x] Add player audio effects
