### ISSUE TITLE
Deploy Site

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#16]
Deployment of site

**Tasks**
- [ ] Deploy site to Netlify
- [ ] Ensure all assets are loaded corrects
- [ ] Ensure relevant build config vars are valid
