### ISSUE TITLE
USER STORY: Homepage and How To Play

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#2]
As a **User**, I want to be greeted with a Homepage that displays a menu of options to easily access information about the game and have a seamless level selection experience so that I can understand the game's mechanics and progress through levels efficiently.

**Acceptance Criteria:**
1. Upon launching the homepage, there should be a clear and visually appealing logo with a menu list that provides the user with all neccesary information, with a clear section of How to play.
2. The "How to play" section should provide concise yet comprehensive details about the game's storyline, objectives, controls, and any unique features.
3. The level selection screen should be easily accessible from the main menu, either directly or through a single interaction.
4. The level select screen should present a clear list of available levels or stages.

**Tasks**
- [x] Create a styled homepage html
- [x] Include storyline, objectives, controls, and mechanics details
- [x] Display list of available levels with names and previews
