### ISSUE TITLE
USER STORY: Game Intro

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#23]
As a **User**, I can see an intro animation so I can feel immersed in the retro experience.

**Acceptance Criteria:**
1. Create an intro html page.
2. Add A story the game. 
3. Tell users what to do to save the world

**Tasks**
- [x] Intro html page
- [x] Style the html page
- [ ] Basic animations with JS.
- [ ] Fade to home page.
