### ISSUE TITLE
Level Assets Sourcing

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#33]
This is a level based game. Each level will be a theme (Mario, Pokemon, Pacman, SpaceInvaders, Sonic, DonkeyKong, Snake).

Source enemies, level design and sounds for each level.
Refer to the mario-tileset.png for guidance.

**Acceptance Criteria**
1. All assets are sourced in the desired format. (16bit) Squares of 16/32/48/64 dimensions with little whitespace surrounding.
2. All whitespace background has been removed. PNG format
3. All extra area has been cropped. 
4. All audio is in mp3 format
5. All images are labelled in a folder related to the level. IE assets> images>mario> mario.png
6. All audio are labelled in a folder related to the level. IE assets> audio>mario> mario.mp3

**Tasks**
- [x] Mario sprites, tile-sets and audio sourced.
- [ ] Pokemon sprites, tile-sets and audio sourced.
- [ ] Pacman sprites, tile-sets and audio sourced.
- [ ] SpaceInvaders sprites, tile-sets and audio sourced.
- [ ] Tetris, tile-sets and audio sourced.

**Comment by DarrachBarneveld** [comment]
**Example tileset**
![Image](https://github.com/DarrachBarneveld/Retroverse-Odyssey/assets/130994206/b139d70b-f952-4a45-b5e6-3d7b60ff5b79)

**Example enemy spritesheet**
![Image](https://github.com/DarrachBarneveld/Retroverse-Odyssey/assets/130994206/770ca947-e6b8-4b73-b54a-23f9b1d11619)

**Comment by SandraBergstrom** [comment]
I go for Mario

**Comment by SandraBergstrom** [comment]
Going for space invaders
