### ISSUE TITLE
USER STORY: Completion Rewards

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#34]
As a **User**, I can view my unlocked trophies so that I know which I have earned and what more I have left to do.

**Acceptance Criteria:**
1. A trophy or medal or prize page.html page should be created.
2. The page should be linked to the home page.
3. Based on level completion prizes are rendered to the page
4. Prizes can be cards with pikachu/mario images on them or anything you desire.
5. Potential abilities in-game by winning these prizes (ie. Pikachu thunder shot in game)

**Tasks**
- [ ] Create a styled trophy/prize/progress.html
- [ ] Rendered prizes based on level completion. (ie level 1 complete = pikachu card rendered)
- [ ] Style prizes to look individual and cool
- [ ] Write a brief description/excerpt about the prize. (ie. Pikachu, a pokemon from pokeworld)

**Comment by DarrachBarneveld** [comment]
**Example prize**
![Image](https://github.com/DarrachBarneveld/Retroverse-Odyssey/assets/130994206/82e3294c-73ba-44a8-9d18-e657bc191f88)

A pokemon card won! Can make with css :)
