### ISSUE TITLE
USER STORY: Game Shooting

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#4]
As a **User**, I can press shoot so that I can fire projectiles at oncoming enemies.

**Acceptance Criteria:**
1. When I press the designated "shoot" button/key, the player's spaceship should fire a bullet immediately.
2. Bullets fired from the spaceship should follow a straight trajectory.
3. Upon firing a bullet a visual effects and sounds should be registered.
4. Bullets should have collision logic 

**Tasks**
- [x] Integrate shooting controls into the player's spaceship.
- [x] Develop bullet sprite or shape to represent the fired projectiles.
- [x] Integrate sound effects for shooting, synchronised with the firing animation.
- [x] Create firing sounds and effects.
- [x] Add collision ability to bullets
