### ISSUE TITLE
USER STORY: Game Enemies

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#6]
As a **User**, I can visually see enemies so that I can avoid and kill them.

**Acceptance Criteria:**
1. Implement basic enemy invader sprites with a distinct visual design.
2. Enemy movements should be horizontal across the map towards the player
3. Enemies should have health that when depleted results in death
4. Enemies should have bullet collision logic
5. Enemies should have collision player logic

**Tasks**
- [x] Create a basic configurable enemy class
- [x] Add health and speed properties.
- [x] Add sprite and movement animations for the enemy
- [x] Add movements for enemies in relation to the map
- [x] Implement collision with player and bullets
- [x] Add death animations and sounds
