### ISSUE TITLE
Pokemon Assets

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Retroverse-Odyssey#71]
We need the following Pokemon assets for a full game experience.

Source enemies, level design and sounds for each level.
Refer to the mario-tileset.png for guidance.

**Acceptance Criteria**
1. All assets are sourced in the desired format. (16bit) Squares of 16/32/48/64 dimensions with little whitespace surrounding.
2. All whitespace background has been removed. PNG format
3. All extra area has been cropped. 
4. All audio is in mp3 format
5. All images are labelled in a folder assets> images>pokemon> pokemon.png
6. All audio are labelled in a folder assets> audio>pokemon> pokemon.mp3
7. Tileset is saved in tilesetfolder

**Tasks**
- [ ] Level tileset for map design
- [ ] Background image (if required)
- [ ] Pokemon Boss Enemy Sprite - Must be relatively large image.
- [ ] Pokemon basic enemy - Small image - spritesheet preferred.
- [ ] Pokemon static enemy - Small image - spritesheet preferred.
- [ ] Boss bullet - Small image - spritesheet preferred.
- [x] Boss audios for each category (Arrive, Hurt, Dead, Shoot).
- [x] Game level music.
